import type { Metadata } from 'next'
import { inter } from '@/utils/font'
import './globals.css'
import { Providers } from '@/providers/providers'
import TopNavbar from '@/components/ui/TopNavbar'
import { cn } from '@/utils/cn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`dark ${inter.className} antialiased`}>
      <body className="w-full dark:bg-black bg-white  dark:bg-grid-white/[0.2] bg-grid-black/[0.2] relative ">
        <TopNavbar />
        <div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
